baseURL = 'https://techfounder.community/'
languageCode = 'en-us'
title = 'Technical Founder Community'
theme = 'paper'
description = 'A community for engineers turned entreprenuers.'

[menu]
[[menu.main]]
identifier = "membership"
name = "Membership"
url = "/membership"
weight = 10
[[menu.main]]
identifier = "contact"
name = "Contact"
url = "/contact"
weight = 30
