name: hugo build

on:
  push:
    branches:
    - master

jobs:
  build-deploy:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@master
      with:
        submodules: true
    - name: build
      uses: briandailey/actions-hugo@master
      if: github.event.deleted == false
      with:
        args: --gc --minify
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_BRANCH: static
